# These are supported funding model platforms

github: xdg6227 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: xgarciadevs # Replace with a single Patreon username
